version: '3.8'

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: borrower_management
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - postgres
    stdin_open: true
    tty: true
